package com.hado90.config.style;

public enum StyleKey {
    TEXT_MAIN_COLOR,
    TEXT_LABEL_COLOR,
    TEXT_DISABLED_COLOR,

    BG_MAIN_COLOR,
    BG_SECONDARY_COLOR,
    BG_DISABLED_COLOR,

    PRIMARY_COLOR_SHADE_MAIN,
    PRIMARY_COLOR_SHADE_ACTIVE,
    PRIMARY_COLOR_SHADE_DISABLED,

    SECONDARY_COLOR_SHADE_MAIN,
    SECONDARY_COLOR_SHADE_ACTIVE,
    SECONDARY_COLOR_SHADE_DISABLED,

    TERTIARY_COLOR_SHADE_MAIN,
    TERTIARY_COLOR_SHADE_ACTIVE,
    TERTIARY_COLOR_SHADE_DISABLED,

    EMO_COLOR_NEG_SHADE_MAIN,
    EMO_COLOR_NEG_SHADE_ACTIVE,
    EMO_COLOR_NEG_SHADE_DISABLED,

    EMO_COLOR_POS_SHADE_MAIN,
    EMO_COLOR_POS_SHADE_ACTIVE,
    EMO_COLOR_POS_SHADE_DISABLED,

    EMO_COLOR_NEU_SHADE_MAIN,
    EMO_COLOR_NEU_SHADE_ACTIVE,
    EMO_COLOR_NEU_SHADE_DISABLED,

    PRIMARY_FONT_FAMILY,
    SECONDARY_FONT_FAMILY,

    SIZE_XS1,
    SIZE_XS2,
    SIZE_XS3,

    SIZE_S1,
    SIZE_S2,
    SIZE_S3,

    SIZE_M1,
    SIZE_M2,
    SIZE_M3,

    SIZE_L1,
    SIZE_L2,
    SIZE_L3,

    SIZE_XL1,
    SIZE_XL2,
    SIZE_XL3,

    SIZE_WIN_WIDTH_S,
    SIZE_WIN_WIDTH_M,
    SIZE_WIN_WIDTH_L,

    SIZE_WIN_HEIGHT_S,
    SIZE_WIN_HEIGHT_M,
    SIZE_WIN_HEIGHT_L,
}
